
-- Dummy Data Gebruiker tabel
INSERT INTO Gebruiker(Gebruiker_id,Gebruikersnaam, email, wachtwoord, is_admin, profiel_zichtbaarheid, collectie_zichtbaarheid, geboorte_datum, beveiligingsvraag) VALUES(1,'honor','something@gmail.com','wachtwoord1',1,1,1,'1996-08-24','nee');
INSERT INTO Gebruiker(Gebruiker_id,Gebruikersnaam, email, wachtwoord, is_admin, profiel_zichtbaarheid, collectie_zichtbaarheid, geboorte_datum, beveiligingsvraag) VALUES(2,'jason','something@hotmail.com','wachtwoord9',0,0,1,'1995-09-24','nee');
INSERT INTO Gebruiker(Gebruiker_id,Gebruikersnaam, email, wachtwoord, is_admin, profiel_zichtbaarheid, collectie_zichtbaarheid, geboorte_datum, beveiligingsvraag) VALUES(3,'marten','something@outlook.com','wachtwoord8',1,0,1,'1994-12-24','veel');
INSERT INTO Gebruiker(Gebruiker_id,gebruikersnaam, email, wachtwoord, is_admin, profiel_zichtbaarheid, collectie_zichtbaarheid, geboorte_datum, beveiligingsvraag) VALUES(4,'pepijn','something@yahoo.com','wachtwoord7',1,0,1,'1993-11-24','ik');
INSERT INTO Gebruiker(Gebruiker_id,gebruikersnaam, email, wachtwoord, is_admin, profiel_zichtbaarheid, collectie_zichtbaarheid, geboorte_datum, beveiligingsvraag) VALUES(5,'nigel','something1@gmail.com','wachtwoord6',1,1,0,'1997-09-24','weet');
INSERT INTO Gebruiker(Gebruiker_id,gebruikersnaam, email, wachtwoord, is_admin, profiel_zichtbaarheid, collectie_zichtbaarheid, geboorte_datum, beveiligingsvraag) VALUES(6,'tsjabbe','something2@gmail.com','wachtwoord5',0,1,1,'1993-07-24','wij');
INSERT INTO Gebruiker(Gebruiker_id,gebruikersnaam, email, wachtwoord, is_admin, profiel_zichtbaarheid, collectie_zichtbaarheid, geboorte_datum, beveiligingsvraag) VALUES(7,'lutsche','something3@gmail.com','wachtwoord4',0,1,1,'1994-05-24','zij');
INSERT INTO Gebruiker(Gebruiker_id,gebruikersnaam, email, wachtwoord, is_admin, profiel_zichtbaarheid, collectie_zichtbaarheid, geboorte_datum, beveiligingsvraag) VALUES(8,'bas','something4@gmail.com','wachtwoord3',1,1,0,'1995-06-24','hij');
INSERT INTO Gebruiker(Gebruiker_id,gebruikersnaam, email, wachtwoord, is_admin, profiel_zichtbaarheid, collectie_zichtbaarheid, geboorte_datum, beveiligingsvraag) VALUES(9,'joris','something5@gmail.com','wachtwoord2',1,0,1,'1997-07-24','ja');
