-- Dummy Data Stripboek tabel 
USE website;
INSERT INTO Stripboek(Boek_id, Reeks, Titel, ISBN, Goedgekeurd, Jaar_v_Uitgave, Uitgever, Afbeelding_urls, Waarde_schatting) VALUES (1, 'Donald Duck', 'Donald Duck: The duckiest book1', 112030405060, '1',  '1996', 'comicbookstore', 'www', 1010);
INSERT INTO Stripboek(Boek_id, Reeks, Titel, ISBN, Goedgekeurd, Jaar_v_Uitgave, Uitgever, Afbeelding_urls, Waarde_schatting) VALUES (2, 'Donald Duck', 'Donald Duck: The duckiest book2', 122030405060, '0', '1997', 'comicbookstore', 'www', 11);
INSERT INTO Stripboek(Boek_id, Reeks, Titel, ISBN, Goedgekeurd, Jaar_v_Uitgave, Uitgever, Afbeelding_urls, Waarde_schatting) VALUES (3, 'Donald Duck', 'Donald Duck: The duckiest book3', 132030405060, '1', '1998', 'comicbookstore', 'www', 90);
INSERT INTO Stripboek(Boek_id, Reeks, Titel, ISBN, Goedgekeurd, Jaar_v_Uitgave, Uitgever, Afbeelding_urls, Waarde_schatting) VALUES (4, 'Donald Duck', 'Donald Duck: The duckiest book4', 142030405060, '0', '1999', 'comicbookstore', 'www', 5);
INSERT INTO Stripboek(Boek_id, Reeks, Titel, ISBN, Goedgekeurd, Jaar_v_Uitgave, Uitgever, Afbeelding_urls, Waarde_schatting) VALUES (5, 'Donald Duck', 'Donald Duck: The duckiest book5', 152030405060, '1', '1992', 'comicbookstore', 'www', 2);
INSERT INTO Stripboek(Boek_id, Reeks, Titel, ISBN, Goedgekeurd, Jaar_v_Uitgave, Uitgever, Afbeelding_urls, Waarde_schatting) VALUES (6, 'Donald Duck', 'Donald Duck: The duckiest book6', 162030405060, '0', '1993', 'comicbookstore', 'www',900);
INSERT INTO Stripboek(Boek_id, Reeks, Titel, ISBN, Goedgekeurd, Jaar_v_Uitgave, Uitgever, Afbeelding_urls, Waarde_schatting) VALUES (7, 'Donald Duck', 'Donald Duck: The duckiest book7', 172030405060, '1', '1994', 'comicbookstore', 'www', 750);
INSERT INTO Stripboek(Boek_id, Reeks, Titel, ISBN, Goedgekeurd, Jaar_v_Uitgave, Uitgever, Afbeelding_urls, Waarde_schatting) VALUES (8, 'Donald Duck', 'Donald Duck: The duckiest book8', 182030405060, '0', '1995', 'comicbookstore', 'www', 600);
INSERT INTO Stripboek(Boek_id, Reeks, Titel, ISBN, Goedgekeurd, Jaar_v_Uitgave, Uitgever, Afbeelding_urls, Waarde_schatting) VALUES (9, 'Donald Duck', 'Donald Duck: The duckiest book9', 192030405060, '1', '1991', 'comicbookstore', 'www', 400);
INSERT INTO Stripboek(Boek_id, Reeks, Titel, ISBN, Goedgekeurd, Jaar_v_Uitgave, Uitgever, Afbeelding_urls, Waarde_schatting) VALUES (10, 'Donald Duck', 'Donald Duck: The duckiest book10', 101030405060, '0', '1990', 'comicbookstore', 'www', 300);
INSERT INTO Stripboek(Boek_id, Reeks, Titel, ISBN, Goedgekeurd, Jaar_v_Uitgave, Uitgever, Afbeelding_urls, Waarde_schatting) VALUES (11, 'Donald Duck', 'Donald Duck: The duckiest book11', 103030405060, '1', '1989', 'comicbookstore', 'www',20);
INSERT INTO Stripboek(Boek_id, Reeks, Titel, ISBN, Goedgekeurd, Jaar_v_Uitgave, Uitgever, Afbeelding_urls, Waarde_schatting) VALUES (12, 'Donald Duck', 'Donald Duck: The duckiest book12', 104030405060, '0', '1986', 'comicbookstore', 'www', 10);
INSERT INTO Stripboek(Boek_id, Reeks, Titel, ISBN, Goedgekeurd, Jaar_v_Uitgave, Uitgever, Afbeelding_urls, Waarde_schatting) VALUES (1000, 'Donald Duck', 'Donald Duck: The duckiest book13', 105030405060, '1', '1987', 'comicbookstore', 'www', 12);